### ISSUE TITLE
Echo off and crash

### ISSUE THREAD

**Issue by ZolnerBen** [PassingTheKnowledge/Batchography#4]
When I run the program it crashes after 5 seconds. Also the echo off statement is showing when the program is open. Could this be due to non ASCII present in other echo statments below possibly?

**Comment by lallousx86** [comment]
Sorry, which program are you talking about? Can you give me more details about the script you are running?

Batch file scripts do not crash. They can do something not expected but themselves, they don't crash like regular native apps.
