### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by ClementAbadie** [PassingTheKnowledge/Batchography#5]
Hi,

Thanks you for your script but unfortunately it does'nt work on French version of Windows.

So I made my own French version  : 

(Just remove the .txt when you download it)

[WifiPasswordReveal_FR.bat](https://github.com/PassingTheKnowledge/Batchography/files/2238658/WifiPasswordReveal_FR.bat)

Best regards,
Clément.

**Comment by lallousx86** [comment]
Thanks Clément,

Can you please test my new script? https://github.com/PassingTheKnowledge/Batchography/blob/master/WifiPasswordReveal.bat

I use the French strings from your changes and updated the script to detect languages accordingly.

**Comment by ClementAbadie** [comment]
Hi,
The version you send me does'nt works : 
```
Reveal all saved WiFi passwords Batch file script v1.0 (c) lallouslab.net

Inspired by the book "Batchography: The Art of Batch Files Programming"

FINDSTR : Argument manquant après /C
FINDSTR : Argument manquant après /C
FINDSTR : Argument manquant après /C
```


( Meaning : "Missing argument after /C" )


I think you forgot to set the vars "%KEYCONTENT%" and  "%ALL_PROFILES%" 😉 

Best regards,
Clément.

**Comment by lallousx86** [comment]
That's weird.

I think something happened during my commits:

Try this revision please: https://raw.githubusercontent.com/PassingTheKnowledge/Batchography/03fa05b4a85d1be93ba99c984e6434e4f590b9ff/WifiPasswordReveal.bat

**Comment by lallousx86** [comment]
Something weird happened with my commits.

I fixed it, please try again:

https://github.com/PassingTheKnowledge/Batchography/blob/master/WifiPasswordReveal.bat

**Comment by ClementAbadie** [comment]
No, sorry.

This is the output : 

```
Reveal all saved WiFi passwords Batch file script v1.1 (c) lallouslab.net

Inspired by the book "Batchography: The Art of Batch Files Programming"

Le lecteur spécifié est introuvable.
Warning: Unknown operating system language detected
lang_id : %a
```

Meaning : Le lecteur spécifié est introuvable. => Specified disk not found.

I added the lang_id echo.

I can look at it later if it can help you.

**Comment by lallousx86** [comment]
Yes please. Give me the value of lang_id.

**Comment by lallousx86** [comment]
Run this command, what do you get?


`reg query "hklm\system\controlset001\control\nls\language" /v Installlanguage`

**Comment by ClementAbadie** [comment]
```
reg query "hklm\system\controlset001\control\nls\language" /v Installlanguag


Erreur : Erreur : le système n’a pas trouvé la clé ou la valeur de Registre spécifiée.
```

Meaning : "ERROR: The system was unable to find the specified registry key or value. "

**Comment by lallousx86** [comment]
Thanks, that explains it! :)

I must install French Windows myself to see if there's a way to detect language!

I don't want the script to ask the user what is your language before it continues...

If you use Regedit.exe, perhaps the registry key is under HKEY_LOCAL_MACHINE -> controlset001 --> control -> nls -> langue?

**Comment by lallousx86** [comment]
Also, can you give me the output of the command:

```
chcp
```

Please?

Thanks.

My output:

```
C:\Users\elias>chcp
Active code page: 437

C:\Users\elias>
```

**Comment by lallousx86** [comment]
Sorry to trouble you, can you also give me the output of:

```
wmic os get OSLanguage /Value
```

Mine:
```
C:\Users\elias>wmic os get OSLanguage /Value


OSLanguage=1033




C:\Users\elias>
```

**Comment by ClementAbadie** [comment]
No problem ! :wink:

I can't find " controlset001 " in the registry...

```
C:\Users\Clément Abadie>chcp
Page de codes active : 850
```

```
C:\Users\Clément Abadie>wmic os get OSLanguage /Value


OSLanguage=1036
```

This command seems to be the better for now.

**Comment by lallousx86** [comment]
Cool, I will update the script again and ask for your feedback. Stay tuned.

Thanks

**Comment by lallousx86** [comment]
Try this one please: https://raw.githubusercontent.com/PassingTheKnowledge/Batchography/master/WifiPasswordReveal.bat

Thanks!

**Comment by ClementAbadie** [comment]
When I run it without the admin privileges :
```
Reveal all saved WiFi passwords Batch file script v1.1 (c) lallouslab.net

Inspired by the book "Batchography: The Art of Batch Files Programming"

French operating system language detected

WiFi: [savedWifi] Password: [xxxxxxxxxx]

Appuyez sur une touche pour continuer...
```

When I run with admin privileges : 

```
Reveal all saved WiFi passwords Batch file script v1.1 (c) lallouslab.net

Inspired by the book "Batchography: The Art of Batch Files Programming"

French operating system language detected

WiFi: [connectedWifi] Password: [xxxxxxxxxxx]
WiFi: [savedWifi] Password: [xxxxxxxxxx]

Appuyez sur une touche pour continuer...

```

I have only 2 saved wifi password on this computer so I can't tell you if it hide the connected one or just show one randomly when running without admin privileges. I can try with my other computer later if you want.

**Comment by lallousx86** [comment]
Well, I will add your script to the REPO for now.


I won't have time to fix the script.

**Comment by lallousx86** [comment]
https://github.com/PassingTheKnowledge/Batchography/commit/9d96b0746e236483be63f70e3909d70c85cacbc2

Thanks!
