### ISSUE TITLE
array-2d.bat

### ISSUE THREAD

**Issue by mariogiganti** [PassingTheKnowledge/Batchography#7]
Hi,
here I'm again with an issue on the   array-2d.bat   script that I downloaded from the Github.com/PassingTheKnowledge repository.
 
This remark of mine is certainly  trivial, but I can't help remarking that on line 3 of the script past the setlocal statement the enabledelayedexpansion syntax should be there.
Otherwise the two-level expansion syntax at row 16 wouldn't work as expected.
  
Mario

**Comment by 0xeb** [comment]
Good catch, thank you Mario. I fixed that.
