### ISSUE TITLE
WifiPasswordReveal: Does not work with profil names containing special characters

### ISSUE THREAD

**Issue by PeterCodar** [PassingTheKnowledge/Batchography#8]
Thanks for this batch.
Unfortunately, it doesn't work with WLAN profile names containing special characters like
`Joe's iPhön`

If you like, you can expand your language detection with the part for a German OS:
```
    if "%lang_id%" == "1031" (
        set KEYCONTENT=Schlüsselinhalt
        set ALL_PROFILES=Profil für alle Benutzer
        echo Deutsches OS erkannt!)
```

**Comment by 0xeb** [comment]
Thanks, added the German support in WifiPasswordReveal-exp.bat!

**Comment by 0xeb** [comment]
Closing and merging with Duplicate of #6
